/** Публичный API движка тактических знаков. */
export * from './vec';
export * from './geo';
export * from './curve';
export * from './model';
export * from './presets';
export { SIDE_COLORS } from './presets-std';
export * from './library';
export { GLYPHS, GLYPH_NAMES } from './render/glyphs';
export * from './factory';
export * from './layers';
export * from './geojson';
export * from './temporal';
export * from './registry';
export * from './cartography';
export * from './ozi';
export * from './scaling';
export { renderDocument, renderFeature, createContext, exportSVG } from './render/index';
export type { RenderResult, RenderedFeature, RenderedLayer, RenderOptions } from './render/index';
export { arrowGeometry, arrowAxisPoints } from './render/arrow';
export { linePath } from './render/line';
