export * from './types';
export * from './rng';
export * from './geo';
export * from './rules';
export { Theatre, decodeGrid, encodeGrid, decodeHeights } from './theatre';
export { step, onMap, createState, issueOrder, targetPoint, profileOf, addHours, supplyHoursOf, supplySources, type SimContext } from './step';
export { frontLine, territoryLine, type FrontOptions } from './front';
export { runScenario, runScenarioWith, compareWithHistory, summarize, checkEvents, type History, type HistoryEvent, type EventResult, type Snapshot, type RunResult, type Deviation } from './history';
export { runToDocument, shortName, type PublishOptions } from './publish';
export { analyze, reportMarkdown, type Analysis, type AnalysisOptions } from './report';
export { contextFrom, rulesFrom, mergeRules, type DataGetter, type DataKind } from './source';
export { snapshotOf } from './history';
export { startGame, playTurn, replayGame, gameOver, gameOutcome, sideStrength, type GameRecord, type GameTurn, type GameState, type GameEnd, type GameOutcome } from './game';
export { unitReports, intelReport, nearbyPlaces, dayEvents, describePlace, describeTarget, detected, detectKm, estimate, areaTitle, areaOriginal, places, orderDelay, rumb, TASK_RU, POSTURE_RU, type UnitReport, type IntelReport, type CombatNote } from './reports';
export { prepareTakeover, checkAction, applyActions, NOT_COMMITTED, type ActionCheck } from './staff';
export { evaluateNorms, normScenarios, measurePace, measureLoss, NORM_MARK, fmtNorm, type Norm, type NormTable, type NormResult, type NormVerdict } from './norms';
export { CALIB_SPACE, CALIB_KEYS, CALIB_INFO, baseParams, rulesWith, scoreRules, evaluateRules, mergeEvaluations, type RulesEvaluation, defaultTrainUntil, Calibrator, calibratedRules, type CalibKey, type CalibParams, type CalibScore } from './calibrate';
export { describeRules, describeProfile, diffRules, rulesOrigin, type ParamRow } from './describe';
export { validateOperation, detectPart, defaultCatalog, defaultLive, type OperationPackage, type CatalogEntry, type LiveSetup, type PackageIssue } from './operation';
export { THEATRE_LAYERS, layerCounts, cropGrid, cropTheatre, layerGeoJSON, recipeFor, theatreToDocument, type BBox, type TheatreLayerId } from './theatre-io';
export { applyInfrastructure, resolveInfra, locatePlace, infraEffect, INFRA_KIND_RU, INFRA_STATE_RU, type InfraRecord, type InfraKind, type InfraState, type InfraResolution } from './infrastructure';
export { OverlayAccumulator, applyOverlay, legendFromSamples, overlayGrid, tilesFor, tileXY, hsv, pixelClass, maskRle, decodeMask, PREVIEW as OVERLAY_COLORS, type OverlayLegend, type OverlayResult, type OverlayApply, type LegendRule } from './overlay';
export { RoadNet, roadNet, visualPath } from './roadnet';
